AWSTemplateFormatVersion: "2010-09-09"
Description: "Create 2 Public and 2 Private Subnets in an existing VPC"

Parameters:
  VpcId:
    Type: String
    Description: "The ID of the existing VPC where Subnets will be created"

  PublicSubnet1Cidr:
    Type: String
    Description: "CIDR block for the first Public Subnet (e.g., 10.0.1.0/24)"
  
  PublicSubnet2Cidr:
    Type: String
    Description: "CIDR block for the second Public Subnet (e.g., 10.0.2.0/24)"
  
  PrivateSubnet1Cidr:
    Type: String
    Description: "CIDR block for the first Private Subnet (e.g., 10.0.3.0/24)"
  
  PrivateSubnet2Cidr:
    Type: String
    Description: "CIDR block for the second Private Subnet (e.g., 10.0.4.0/24)"
  
  AvailabilityZone1:
    Type: String
    Description: "The Availability Zone for the first pair of Subnets (e.g., us-east-1a)"
  
  AvailabilityZone2:
    Type: String
    Description: "The Availability Zone for the second pair of Subnets (e.g., us-east-1b)"

Resources:
  # Public Subnet 1
  PublicSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VpcId
      CidrBlock: !Ref PublicSubnet1Cidr
      AvailabilityZone: !Ref AvailabilityZone1
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}-Public-Subnet-1"

  # Public Subnet 2
  PublicSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VpcId
      CidrBlock: !Ref PublicSubnet2Cidr
      AvailabilityZone: !Ref AvailabilityZone2
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}-Public-Subnet-2"

  # Private Subnet 1
  PrivateSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VpcId
      CidrBlock: !Ref PrivateSubnet1Cidr
      AvailabilityZone: !Ref AvailabilityZone1
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}-Private-Subnet-1"

  # Private Subnet 2
  PrivateSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VpcId
      CidrBlock: !Ref PrivateSubnet2Cidr
      AvailabilityZone: !Ref AvailabilityZone2
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}-Private-Subnet-2"

  # Internet Gateway (for Public Subnets)
  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}-IGW"

  AttachInternetGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref VpcId
      InternetGatewayId: !Ref InternetGateway

  # Public Route Table
  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VpcId
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}-Public-Route-Table"

  PublicRoute:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: "0.0.0.0/0"
      GatewayId: !Ref InternetGateway

  # Associate Public Subnets with Public Route Table
  PublicSubnet1RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet1
      RouteTableId: !Ref PublicRouteTable

  PublicSubnet2RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet2
      RouteTableId: !Ref PublicRouteTable

Outputs:
  PublicSubnet1Id:
    Description: "ID of the first Public Subnet"
    Value: !Ref PublicSubnet1

  PublicSubnet2Id:
    Description: "ID of the second Public Subnet"
    Value: !Ref PublicSubnet2

  PrivateSubnet1Id:
    Description: "ID of the first Private Subnet"
    Value: !Ref PrivateSubnet1

  PrivateSubnet2Id:
    Description: "ID of the second Private Subnet"
    Value: !Ref PrivateSubnet2
