AWSTemplateFormatVersion: "2010-09-09"
Description: "Web Server Security Group with HTTP and HTTPS access"

Parameters:
  VpcId:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /cloudformation/networking/VpcId
    Description: "The ID of the existing VPC where Subnets will be created"

Resources:
  WebServerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub "${AWS::StackName}-WebServerSG"
      GroupDescription: "Security Group for Web Server (HTTP, HTTPS)"
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
          Description: "Allow HTTP traffic from anywhere"
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0
          Description: "Allow HTTPS traffic from anywhere"
      SecurityGroupEgress:
        - IpProtocol: -1
          FromPort: -1
          ToPort: -1
          CidrIp: 0.0.0.0/0
          Description: "Allow all outbound traffic"

Outputs:
  SecurityGroupId:
    Description: "ID of the created Web Server Security Group"
    Value: !Ref WebServerSecurityGroup
