apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
data:
  MYSQL_DATABASE: {mysql-database}
  my.cnf: |
    [mysqld]
    character-set-server=utf8mb4
    collation-server=utf8mb4_unicode_ci
    default_authentication_plugin=mysql_native_password
    max_connections=200
    
    [client]
    default-character-set=utf8mb4
    
    [mysql]
    default-character-set=utf8mb4 