apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      labels:
        app: django
    spec:
      containers:
      - name: django
        image: ghcr.io/baobabnamu/goormthon/team-mission-kubernetes-django-dev:latest
        ports:
        - containerPort: 8000
        command: ["/bin/sh", "-c"]
        args:
          - python manage.py migrate &&
            python manage.py createsuperuser --noinput --username ${DJANGO_SUPERUSER_USERNAME} --email ${DJANGO_SUPERUSER_EMAIL} || true &&
            python manage.py runserver 0.0.0.0:8000
        env:
        - name: DEBUG
          valueFrom:
            configMapKeyRef:
              name: django-config
              key: DEBUG
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: django-secret
              key: MYSQL_ROOT_PASSWORD
        - name: DJANGO_SUPERUSER_USERNAME
          valueFrom:
            secretKeyRef:
              name: django-secret
              key: DJANGO_SUPERUSER_USERNAME
        - name: DJANGO_SUPERUSER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: django-secret
              key: DJANGO_SUPERUSER_PASSWORD
        - name: DJANGO_SUPERUSER_EMAIL
          valueFrom:
            secretKeyRef:
              name: django-secret
              key: DJANGO_SUPERUSER_EMAIL
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: django-secret
              key: DB_NAME
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: django-secret
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: django-secret
              key: DB_PASSWORD
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: django-secret
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            secretKeyRef:
              name: django-secret
              key: DB_PORT
        envFrom:
        - configMapRef:
            name: django-config
        - secretRef:
            name: django-secret